### ISSUE TITLE
Build failure in M1 Mac

### ISSUE THREAD

**Issue by ChangheeOh** [ponychicken/WebsterParser#77]
I followed the instructions for installation which described in your README.md and I found the following errors at the last step.
Please review and provide some guides.

- Hardware: M1 Macbook Air
- OS version: 
  + ProductName: macOS
  + ProductVersion: 12.5
  + BuildVersion: 21G72
- Related SW version:
  + Node.js: v18.7.0
  + Xcode: Version 13.4.1 (13F100)
  + Additional Tools for Xcode (Includes Apple's Dictionary Developer Kit): 13.4
  + npm: 8.15.0

```
 ~/work/repos/WebsterParser/ [main*] npm run build_and_install
> websterparser@1.3.6 build_and_install
> npm start && cd template && make && make install


> websterparser@1.3.6 start
> ts-node index.ts

Finished reading files: [
  'srcFiles/CIDE.A', 'srcFiles/CIDE.B',
  'srcFiles/CIDE.C', 'srcFiles/CIDE.D',
  'srcFiles/CIDE.E', 'srcFiles/CIDE.F',
  'srcFiles/CIDE.G', 'srcFiles/CIDE.H',
  'srcFiles/CIDE.I', 'srcFiles/CIDE.J',
  'srcFiles/CIDE.K', 'srcFiles/CIDE.L',
  'srcFiles/CIDE.M', 'srcFiles/CIDE.N',
  'srcFiles/CIDE.O', 'srcFiles/CIDE.P',
  'srcFiles/CIDE.Q', 'srcFiles/CIDE.R',
  'srcFiles/CIDE.S', 'srcFiles/CIDE.T',
  'srcFiles/CIDE.U', 'srcFiles/CIDE.V',
  'srcFiles/CIDE.W', 'srcFiles/CIDE.X',
  'srcFiles/CIDE.Y', 'srcFiles/CIDE.Z'
]
TypeError: Cannot read properties of undefined (reading 'xmlMode')
    at LoadedCheerio.find (/Users/och/work/repos/WebsterParser/node_modules/cheerio/lib/api/https:/raw.githubusercontent.com/cheeriojs/cheerio/d1cbc66d53392ce8bf6cd0068f675836372d2bf3/src/api/traversing.ts:75:27)
    at /Users/och/work/repos/WebsterParser/index.ts:259:17
    at Element.<anonymous> (/Users/och/work/repos/WebsterParser/util.ts:13:28)
    at LoadedCheerio.each (/Users/och/work/repos/WebsterParser/node_modules/cheerio/lib/api/https:/raw.githubusercontent.com/cheeriojs/cheerio/d1cbc66d53392ce8bf6cd0068f675836372d2bf3/src/api/traversing.ts:581:24)
    at forEach (/Users/och/work/repos/WebsterParser/util.ts:13:7)
    at parseFile (/Users/och/work/repos/WebsterParser/index.ts:252:10)
    at Object.callback (/Users/och/work/repos/WebsterParser/index.ts:232:7)
    at /Users/och/work/repos/WebsterParser/node_modules/async/dist/async.js:1558:26
    at /Users/och/work/repos/WebsterParser/node_modules/async/dist/async.js:327:20
    at /Users/och/work/repos/WebsterParser/index.ts:224:46
```

**Comment by jeffbyrnes** [comment]
@ChangheeOh are you still having this issue? I’m able to build the dictionary on my M3 iMac:

```bash
🕙 17:18:00 jeffbyrnes in WebsterParser on  main [!?] via  v21.6.1
♠ npm run build

> websterparser@1.3.7 build
> npm start && cd template && make


> websterparser@1.3.7 start
> ts-node index.ts

Finished reading files: [
# [snip]
- Building key_text index.
- Building reference index.
- Fixing dictionary property.
- Copying CSS.
- Copying other resources.
- Finished building ./objects/Webster's Unabridged Dictionary (1913).dictionary.
echo "Done."
Done.
```

**Comment by ChangheeOh** [comment]
I removed older repository and newly cloned the latest one and retry install as follow.
But still have a new issue.

1) NEW issue found
```
**"""/Applications/Utilities/Dictionary Development Kit"/bin"/build_dict.sh" -v 10.11  "Webster's Unabridged Dictionary (1913)" dict.xml styles.css info.plist
/bin/sh: /Applications/Utilities/Dictionary Development Kit/bin/build_dict.sh: No such file or directory
make: *** [all] Error 127**
```

2) Full install log
```
 ~/work/repos/WebsterParser/ [main*] npm run build_and_install

> websterparser@1.3.7 build_and_install
> npm start && cd template && make && make install


> websterparser@1.3.7 start
> ts-node index.ts

Finished reading files: [
  'srcFiles/CIDE.A', 'srcFiles/CIDE.B',
  'srcFiles/CIDE.C', 'srcFiles/CIDE.D',
  'srcFiles/CIDE.E', 'srcFiles/CIDE.F',
  'srcFiles/CIDE.G', 'srcFiles/CIDE.H',
  'srcFiles/CIDE.I', 'srcFiles/CIDE.J',
  'srcFiles/CIDE.K', 'srcFiles/CIDE.L',
  'srcFiles/CIDE.M', 'srcFiles/CIDE.N',
  'srcFiles/CIDE.O', 'srcFiles/CIDE.P',
  'srcFiles/CIDE.Q', 'srcFiles/CIDE.R',
  'srcFiles/CIDE.S', 'srcFiles/CIDE.T',
  'srcFiles/CIDE.U', 'srcFiles/CIDE.V',
  'srcFiles/CIDE.W', 'srcFiles/CIDE.X',
  'srcFiles/CIDE.Y', 'srcFiles/CIDE.Z'
]
Parsed 0 Front/Back Matter
Parsed 1000 Abstemious
Parsed 2000 achromatise
Parsed 3000 Adjunctive
Parsed 4000 Affine
Parsed 5000 Air chamber
Parsed 6000 Allowance
Parsed 7000 Ammodytidae
Parsed 8000 Anger
Parsed 9000 Anthropotomist
Parsed 10000 Appearance
Parsed 11000 Architector
Parsed 12000 Articulation
Parsed 13000 Assume
Parsed 14000 Aubaine
Parsed 15000 Await
Parsed 0 Front/Back Matter
Parsed 1000 Balm
Parsed 2000 Basi-
Parsed 3000 Beaver
Parsed 4000 Bench
Parsed 5000 Bibelot
Parsed 6000 Bite
Parsed 7000 Blissom
Parsed 8000 Bogey
Parsed 9000 Boss
Parsed 10000 Branchiferous
Parsed 11000 Brighten
Parsed 12000 Buddhistic
Parsed 13000 Bushido
Parsed 0 Front/Back Matter
Parsed 1000 Camber
Parsed 2000 Capriccio
Parsed 3000 Caryopsis
Parsed 4000 Cave
Parsed 5000 Chain
Parsed 6000 Chaw
Parsed 7000 Chlorophyll
Parsed 8000 Circuit
Parsed 9000 Clear-shining
Parsed 10000 Coachmanship
Parsed 11000 Cold
Parsed 12000 Commend
Parsed 13000 Comply
Parsed 14000 Condition
Parsed 15000 Connaturality
Parsed 16000 Contain
Parsed 17000 Convertible
Parsed 18000 Coronoid
Parsed 19000 Countermine
Parsed 20000 Crane
Parsed 21000 Criticise
Parsed 22000 Crystalline
Parsed 23000 Custom
Parsed 0 Front/Back Matter
Parsed 1000 Daydream
Parsed 2000 Deconcentrate
Parsed 3000 Deity
Parsed 4000 Dentate-ciliate
Parsed 5000 Design
Parsed 6000 Dexterous
Parsed 7000 Dilacerate
Parsed 8000 Discern
Parsed 9000 Dishonorable
Parsed 10000 Dissertate
Parsed 11000 Division
Parsed 12000 Dosser
Parsed 13000 Dray
Parsed 14000 Duds
Parsed 0 Front/Back Matter
Parsed 1000 Effection
Parsed 2000 Eliquament
Parsed 3000 -en
Parsed 4000 enlistee
Parsed 5000 Epigraph
Parsed 6000 Escutcheon
Parsed 7000 Every
Parsed 8000 Exile
Parsed 9000 Extirpate
Parsed 0 Front/Back Matter
Parsed 1000 Fang
Parsed 2000 fedayee
Parsed 3000 Fico
Parsed 4000 Firmless
Parsed 5000 Flesh
Parsed 6000 Fly
Parsed 7000 Forego
Parsed 8000 Founder
Parsed 9000 frilled
Parsed 10000 Funk
Parsed 0 G
Parsed 1000 Gastro-
Parsed 2000 Germain
Parsed 3000 Glaucous
Parsed 4000 Goitre
Parsed 5000 Grandmother
Parsed 6000 Grist
Parsed 7000 Gutturalness
Parsed 0 H
Parsed 1000 Handsel
Parsed 2000 Haw
Parsed 3000 Heir
Parsed 4000 Heterogenesis
Parsed 5000 Hoarse
Parsed 6000 Hook
Parsed 7000 Hull
Parsed 8000 Hyoid
Parsed 0 Front/Back Matter
Parsed 1000 Imbecile
Parsed 2000 Importless
Parsed 3000 Incident
Parsed 4000 Indemnity
Parsed 5000 Inexpediency
Parsed 6000 Inheritance
Parsed 7000 Inspiration
Parsed 8000 Interference
Parsed 9000 Intrusive
Parsed 10000 Irrisible
Parsed 0 J
Parsed 1000 Job
Parsed 2000 Justify
Parsed 0 Front/Back Matter
Parsed 1000 Kinship
Parsed 0 Front/Back Matter
Parsed 1000 Language
Parsed 2000 Lay
Parsed 3000 Leonine
Parsed 4000 Ligature
Parsed 5000 Liquidate
Parsed 6000 Lofty
Parsed 7000 Low
Parsed 0 M
Parsed 1000 main street
Parsed 2000 Manifestness
Parsed 3000 Martyrize
Parsed 4000 Mean
Parsed 5000 Mensurableness
Parsed 6000 Mezzo-rilievo
Parsed 7000 Minor
Parsed 8000 Mite
Parsed 9000 Monocrat
Parsed 10000 Moste
Parsed 11000 Mumble
Parsed 0 N
Parsed 1000 Need
Parsed 2000 Nide
Parsed 3000 no-nonsense
Parsed 4000 numinous
Parsed 0 O
Parsed 1000 Octodentate
Parsed 2000 One
Parsed 3000 Order
Parsed 4000 Ought
Parsed 5000 Overhand
Parsed 0 P
Parsed 1000 Pan
Parsed 2000 Pardale
Parsed 3000 Passport
Parsed 4000 Pedagogics
Parsed 5000 Perch
Parsed 6000 Pertusate
Parsed 7000 Photogrammetry
Parsed 8000 Pimiento
Parsed 9000 Plank
Parsed 10000 Plunge
Parsed 11000 Polymnite
Parsed 12000 Post-fine
Parsed 13000 Precision
Parsed 14000 Presswork
Parsed 15000 Proceed
Parsed 16000 Propenyl
Parsed 17000 Prytaneum
Parsed 18000 Purge
Parsed 0 Front/Back Matter
Parsed 1000 Quintain
Parsed 0 R
Parsed 1000 Ransack
Parsed 2000 Reason
Parsed 3000 recuse
Parsed 4000 Regimental
Parsed 5000 Remotion
Parsed 6000 Rerefief
Parsed 7000 Reticulation
Parsed 8000 Rhus
Parsed 9000 Rivose
Parsed 10000 Roughdraw
Parsed 11000 Run
Parsed 0 Front/Back Matter
Parsed 1000 Sampler
Parsed 2000 Scald
Parsed 3000 Scorch
Parsed 4000 Sea holm
Parsed 5000 Selah
Parsed 6000 Septate
Parsed 7000 Sextodecimo
Parsed 8000 Shibboleth
Parsed 9000 Shuck
Parsed 10000 Sin
Parsed 11000 Skit
Parsed 12000 Sluice
Parsed 13000 Snuffer
Parsed 14000 Song
Parsed 15000 Spark
Parsed 16000 Spindleshanks
Parsed 17000 Springe
Parsed 18000 Stammer
Parsed 19000 Steerage
Parsed 20000 Stockdove
Parsed 21000 Stretch
Parsed 22000 Suable
Parsed 23000 Succession
Parsed 24000 Superior
Parsed 25000 Sutor
Parsed 26000 Symmetrize
Parsed 0 T
Parsed 1000 Tap
Parsed 2000 Telltale
Parsed 3000 Testate
Parsed 4000 Thickening
Parsed 5000 Thwart
Parsed 6000 To
Parsed 7000 Tortoise
Parsed 8000 Trance
Parsed 9000 Trespass
Parsed 10000 Troopfowl
Parsed 11000 Turbinal
Parsed 0 Front/Back Matter
Parsed 1000 Underboard
Parsed 2000 Uniformly
Parsed 3000 Unsurmountable
Parsed 4000 Usufructuary
Parsed 0 V
Parsed 1000 Vedanta
Parsed 2000 Vestigial
Parsed 3000 Vital
Parsed 0 Front/Back Matter
Parsed 1000 Warpath
Parsed 2000 Weakness
Parsed 3000 What
Parsed 4000 Who
Parsed 5000 Wisdom
Parsed 6000 Worm
Parsed 0 X
Parsed 0 Y
Parsed 0 Z
Everything was parsed
Unknown entities: colret, ai, dot
Parts of speech: 17
Unknown parts of speech: 17
Postprocessing 108654 entries...
Postprocessing entry 0 0
Postprocessing entry 1000 Achromatize
Postprocessing entry 2000 AEthogen
Postprocessing entry 3000 alkalotic
Postprocessing entry 4000 Anacardiaceous
Postprocessing entry 5000 Anthypnotic
Postprocessing entry 6000 Arbitrarious
Postprocessing entry 7000 asserting
Postprocessing entry 8000 Average
Postprocessing entry 9000 Barnstorm
Postprocessing entry 10000 Bemonster
Postprocessing entry 11000 Birthdom
Postprocessing entry 12000 Bombycid
Postprocessing entry 13000 brickfield
Postprocessing entry 14000 Butterfly
Postprocessing entry 15000 Cantonal
Postprocessing entry 16000 cationic
Postprocessing entry 17000 Chartist
Postprocessing entry 18000 Churlishly
Postprocessing entry 19000 Clysmian
Postprocessing entry 20000 Committal
Postprocessing entry 21000 Connate
Postprocessing entry 22000 Cordy
Postprocessing entry 23000 Craniometry
Postprocessing entry 24000 Cumbrian
Postprocessing entry 25000 De-
Postprocessing entry 26000 Deliquescent
Postprocessing entry 27000 Detergency
Postprocessing entry 28000 Diplex
Postprocessing entry 29000 Disproperty
Postprocessing entry 30000 Dossil
Postprocessing entry 31000 Dwang
Postprocessing entry 32000 Electro-puncturing
Postprocessing entry 33000 energise
Postprocessing entry 34000 Equipedal
Postprocessing entry 35000 Exaspidean
Postprocessing entry 36000 Fabricate
Postprocessing entry 37000 Festoony
Postprocessing entry 38000 Flinders
Postprocessing entry 39000 Forth
Postprocessing entry 40000 Funest
Postprocessing entry 41000 Genesiolgy
Postprocessing entry 42000 Goad
Postprocessing entry 43000 Gromwell
Postprocessing entry 44000 Hamlet
Postprocessing entry 45000 Helter-skelter
Postprocessing entry 46000 Hittorf tube
Postprocessing entry 47000 Humblebee
Postprocessing entry 48000 Idiomorphous
Postprocessing entry 49000 Impudency
Postprocessing entry 50000 Indorse
Postprocessing entry 51000 Insense
Postprocessing entry 52000 Intrenchment
Postprocessing entry 53000 jailed
Postprocessing entry 54000 Kerb
Postprocessing entry 55000 Laird
Postprocessing entry 56000 Leguleian
Postprocessing entry 57000 Lisp
Postprocessing entry 58000 Lumbaginous
Postprocessing entry 59000 Mala
Postprocessing entry 60000 Martialist
Postprocessing entry 61000 Mention
Postprocessing entry 62000 Mina
Postprocessing entry 63000 Moliminous
Postprocessing entry 64000 Mucic
Postprocessing entry 65000 Nascent
Postprocessing entry 66000 niobium
Postprocessing entry 67000 Nummary
Postprocessing entry 68000 Olla
Postprocessing entry 69000 Oscillatoria
Postprocessing entry 70000 oversexed
Postprocessing entry 71000 Pansclavonian
Postprocessing entry 72000 Patrolman
Postprocessing entry 73000 Peribolos
Postprocessing entry 74000 Phonetist
Postprocessing entry 75000 Pitiful
Postprocessing entry 76000 Polo
Postprocessing entry 77000 Prankish
Postprocessing entry 78000 Probationership
Postprocessing entry 79000 Psilanthropism
Postprocessing entry 80000 Quarreling
Postprocessing entry 81000 Ray
Postprocessing entry 82000 Regimentals
Postprocessing entry 83000 Respirability
Postprocessing entry 84000 Rixatrix
Postprocessing entry 85000 Sad
Postprocessing entry 86000 Scaroid
Postprocessing entry 87000 Secernment
Postprocessing entry 88000 Sericeous
Postprocessing entry 89000 Sic
Postprocessing entry 90000 Slipcoat cheese
Postprocessing entry 91000 Sorn
Postprocessing entry 92000 Sporadic
Postprocessing entry 93000 Stiacciato
Postprocessing entry 94000 Subcostal
Postprocessing entry 95000 Superseminate
Postprocessing entry 96000 Systematizer
Postprocessing entry 97000 Temporalty
Postprocessing entry 98000 This
Postprocessing entry 99000 Topiary
Postprocessing entry 100000 Triangulares
Postprocessing entry 101000 Turkism
Postprocessing entry 102000 Undergroan
Postprocessing entry 103000 Unsay
Postprocessing entry 104000 Vaporability
Postprocessing entry 105000 Virtue
Postprocessing entry 106000 Waterless
Postprocessing entry 107000 Wiggler
Postprocessing entry 108000 Yaup
Done; starting to build XML
Building xml
Wrote file
Wrote file
**"""/Applications/Utilities/Dictionary Development Kit"/bin"/build_dict.sh" -v 10.11  "Webster's Unabridged Dictionary (1913)" dict.xml styles.css info.plist
/bin/sh: /Applications/Utilities/Dictionary Development Kit/bin/build_dict.sh: No such file or directory
make: *** [all] Error 127**
```

**Comment by jeffbyrnes** [comment]
This is because you didn’t install the Dictionary Development Kit. Please review the README to learn how to download & install that kit, then this should work.

**Comment by ChangheeOh** [comment]
Thanks for your kind help and finally succeeded to install.
